In [15]:
import os
import requests
import pandas as pd

path = './data/raw'
nav_schemes = {
    "hdfc": "125497",
    "SBI_Bluechip": "119551",
    "ICICI_Bluechip": "120503",
    "Nippon_Large_Cap": "118632",
    "Axis_Bluechip": "119092",
    "Kotak_Bluechip": "120841"
}
for name, code in nav_schemes.items():
    try:
        api_url = f"https://api.mfapi.in/mf/{code}"
        json_data = requests.get(api_url).json()
        print(f"\n---Scheme name: {name} (Code: {code}) ---")
        print("Keys:", json_data.keys())      
        print("First Row:", json_data['data'][0])  
        nav_list = json_data['data']
        df_scheme = pd.DataFrame(nav_list)
        file_name = f"live_{name}_nav.csv"
        full_path = os.path.join(path, file_name)
        df_scheme.to_csv(full_path, index=False)
        print(f"Saved successfully at: {full_path}")
        display(df_scheme.head(2))

    except Exception as e:
        print(e)

---Scheme name: hdfc (Code: 125497) ---
Keys: dict_keys(['meta', 'data', 'status'])
First Row: {'date': '03-06-2026', 'nav': '194.08100'}
Saved successfully at: ./data/raw\live_hdfc_nav.csv

         date        nav
0  03-06-2026  194.08100
1  02-06-2026  193.12950

---Scheme name: SBI_Bluechip (Code: 119551) ---
Keys: dict_keys(['meta', 'data', 'status'])
First Row: {'date': '03-06-2026', 'nav': '104.74960'}
Saved successfully at: ./data/raw\live_SBI_Bluechip_nav.csv

         date        nav
0  03-06-2026  104.74960
1  02-06-2026  104.76630

---Scheme name: ICICI_Bluechip (Code: 120503) ---
Keys: dict_keys(['meta', 'data', 'status'])
First Row: {'date': '03-06-2026', 'nav': '103.48090'}
Saved successfully at: ./data/raw\live_ICICI_Bluechip_nav.csv

         date        nav
0  03-06-2026  103.48090
1  02-06-2026  103.59590

---Scheme name: Nippon_Large_Cap (Code: 118632) ---
Keys: dict_keys(['meta', 'data', 'status'])
First Row: {'date': '03-06-2026', 'nav': '97.21670'}
Saved successfully at: ./data/raw\live_Nippon_Large_Cap_nav.csv

         date       nav
0  03-06-2026  97.21670
1  02-06-2026  97.47830

---Scheme name: Axis_Bluechip (Code: 119092) ---
Keys: dict_keys(['meta', 'data', 'status'])
First Row: {'date': '03-06-2026', 'nav': '6159.96260'}
Saved successfully at: ./data/raw\live_Axis_Bluechip_nav.csv

         date         nav
0  03-06-2026  6159.96260
1  02-06-2026  6158.96650

---Scheme name: Kotak_Bluechip (Code: 120841) ---
Keys: dict_keys(['meta', 'data', 'status'])
First Row: {'date': '03-06-2026', 'nav': '245.65930'}
Saved successfully at: ./data/raw\live_Kotak_Bluechip_nav.csv

         date        nav
0  03-06-2026  245.65930
1  02-06-2026  246.85660

In [5]:
import pandas as pd
import os
path='./data/raw/01_fund_master.csv'
try:
        df_master=pd.read_csv(path)
        print("All Distinct Fund Houses:")
        print(df_master['fund_house'].unique())
        print('*' * 50)
        print("All Distinct Categories:")
        print(df_master['category'].unique())
        print('*' * 50)
        print(" All Distinct Sub-Categories:")
        print(df_master['sub_category'].unique())
        print('*' * 50)
        print(df_master['risk_category'].unique())
except FileNotFoundError as e:
        print(e)

All Distinct Fund Houses:
['SBI Mutual Fund' 'HDFC Mutual Fund' 'ICICI Prudential MF'
 'Nippon India MF' 'Kotak Mahindra MF' 'Axis Mutual Fund'
 'Aditya Birla Sun Life MF' 'UTI Mutual Fund' 'Mirae Asset MF'
 'DSP Mutual Fund']
**************************************************
All Distinct Categories:
['Equity' 'Debt']
**************************************************
 All Distinct Sub-Categories:
['Large Cap' 'Small Cap' 'Gilt' 'Mid Cap' 'Short Duration' 'Value'
 'Liquid' 'Index/ETF' 'Flexi Cap' 'Index' 'Large & Mid Cap' 'ELSS']
**************************************************
['Moderate' 'Very High' 'Low' 'High' 'Moderately High']

In [12]:
import os
import pandas as pd
path = "./data/raw/01_fund_master.csv"
try:
    df_master = pd.read_csv(path)
    print("\n---VALIDATING AMFI CODES ---")
    master_codes = set(df_master["amfi_code"].unique())
    print(f" Master File  {len(master_codes)}")
    fetched_codes = {125497, 119551, 120503, 118632, 119092, 120841}
    validated_count = len(master_codes & fetched_codes)
    missing_codes = master_codes - fetched_codes
    print(f"Successfully Validated Codes: {validated_count}")
    print(f"Unfetched Codes: {len(missing_codes)}")
except FileNotFoundError as e:
    print(e)

---VALIDATING AMFI CODES ---
 Master File  40
Successfully Validated Codes: 6
Unfetched Codes: 34